<?php

namespace ContainerWGQOeg5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExamplePageTwoControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TYGoHWB.App\Controller\ExamplePageTwoController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TYGoHWB.App\\Controller\\ExamplePageTwoController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'formFactory' => ['privates', 'form.factory', 'getForm_FactoryService', true],
        ], [
            'formFactory' => '?',
        ]))->withContext('App\\Controller\\ExamplePageTwoController::index()', $container);
    }
}
