<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ5TYP2Q\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ5TYP2Q/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ5TYP2Q.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ5TYP2Q\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ5TYP2Q\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z5TYP2Q',
    'container.build_id' => '832d73e8',
    'container.build_time' => 1744371790,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ5TYP2Q');
