<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU3PT20X\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU3PT20X/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU3PT20X.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU3PT20X\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU3PT20X\App_KernelDevDebugContainer([
    'container.build_hash' => 'U3PT20X',
    'container.build_id' => '292c3ddb',
    'container.build_time' => 1744182862,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU3PT20X');
