<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWXHB6px\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWXHB6px/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWXHB6px.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWXHB6px\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWXHB6px\App_KernelDevDebugContainer([
    'container.build_hash' => 'WXHB6px',
    'container.build_id' => 'a3b94aa7',
    'container.build_time' => 1744131452,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWXHB6px');
