<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_example_page' => [[], ['_controller' => 'App\\Controller\\ExamplePageController::index'], [], [['text', '/examplePage']], [], [], []],
    'rezerwuj_prezent' => [[], ['_controller' => 'App\\Controller\\ExamplePageController::rezerwujPrezent'], [], [['text', '/rezerwujPrezent']], [], [], []],
    'app_example_page_two' => [[], ['_controller' => 'App\\Controller\\ExamplePageTwoController::index'], [], [['text', '/example/page/two']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\ExamplePageController::index' => [[], ['_controller' => 'App\\Controller\\ExamplePageController::index'], [], [['text', '/examplePage']], [], [], []],
    'App\Controller\ExamplePageController::rezerwujPrezent' => [[], ['_controller' => 'App\\Controller\\ExamplePageController::rezerwujPrezent'], [], [['text', '/rezerwujPrezent']], [], [], []],
    'App\Controller\ExamplePageTwoController::index' => [[], ['_controller' => 'App\\Controller\\ExamplePageTwoController::index'], [], [['text', '/example/page/two']], [], [], []],
    'App\Controller\HomeController::index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
];
